# Generated by Django 3.0 on 2020-01-21 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_blogs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogs',
            options={'ordering': ('title',), 'verbose_name_plural': 'Blogs'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('name',), 'verbose_name_plural': 'Contacts'},
        ),
    ]
